spring.config.import=classpath:rabbitmq.properties

spring.main.web-application-type=none

spring.mail.host=localhost
spring.mail.port=1025

notification.mail.from=noreply@dijkstra.local
notification.mail.from-name=Dijkstra Service

rabbitmq.queue.user-created=notification.user.created
