spring.main.web-application-type=none

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

spring.mail.host=localhost
spring.mail.port=1025

notification.mail.from=noreply@dijkstra.local
notification.mail.from-name=Dijkstra Service

rabbitmq.exchange=dijkstra.events
rabbitmq.queue.user-created=notification.user.created
rabbitmq.routing-key.user-created=user.created
