mongodb.map.uri=mongodb://admin:password@localhost:27017/dijkstra-map?authSource=admin
mongodb.map.database=dijkstra-map
mongodb.users.uri=mongodb://admin:password@localhost:27017/dijkstra-users?authSource=admin

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password
rabbitmq.exchange=dijkstra.events
rabbitmq.queue.route-recalculation=map-service.route-recalculation
rabbitmq.queue.route-recalculated=notification.route.recalculated
rabbitmq.routing-key.route-recalculated=route.recalculated
