mongodb.map.uri=mongodb://admin:password@localhost:27017/dijkstra-map?authSource=admin
mongodb.map.database=dijkstra-map
mongodb.users.uri=mongodb://admin:password@localhost:27017/dijkstra-users?authSource=admin
