spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

rabbitmq.exchange=dijkstra.events
rabbitmq.routing-key.user-created=user.created
rabbitmq.routing-key.route-recalculated=route.recalculated
rabbitmq.queue.route-recalculated=notification.route.recalculated
