server.port=8081
mongodb.uri=mongodb://admin:password@localhost:27017/dijkstra-users?authSource=admin
mongodb.database=dijkstra-users
token.expiration-ms=86400000

admin.default.password=admin

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

rabbitmq.exchange=dijkstra.events
rabbitmq.routing-key.user-created=user.created

temp.password.expiration-ms=600000
